name: Create S3 Bucket

on:
  push:
    branches:
      - devlopment
jobs:
  create_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check if S3 bucket exists
        run: |
          aws s3api head-bucket --bucket my-s3-bucket-name --region us-east-1 2>/dev/null || exit 0
          echo "Bucket already exists"
          exit 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Create S3 bucket
        run: aws s3api create-bucket --bucket my-s3-bucket-name --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
